on:
  - push

jobs:
  build:
    uses: cloud-cli/workflows/.github/workflows/docker-ghcr-build.yml@main
    with:
      name: cloud-cli/dummy
      baseImage: my-org/node:6437bc4ff8c2e07f9f3d8ef2c9022ceaa6c3a435
      defaultBranch: main
